export const ActionTypes = {
  AUTH: "AUTH",
  LOGOUT: "LOGOUT",
  FETCH_ALL_USER: "FETCH_ALL",
  CHANGE_USER_TAB: "CHANGE_USER_TAB",
  FETCH_ALL_MESSAGES: "FETCH_ALL_MESSAGES",
  POST_MESSAGE: "POST_MESSAGE",
};
